import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "@/Components/Header";
import {Container} from "@mui/system";
import Hero from "@/Components/Hero";
import Featured from "@/Components/Featured";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Container maxWidth={'xl'} >
            <Header/>

            <Hero/>
            <Featured/>
        </Container>
    </>
  )
}
